"""initial schema

Revision ID: d7b9e6c904e4
Revises: 
Create Date: 2026-04-26 11:38:47.939772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b9e6c904e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_username'), ['username'], unique=True)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('student_name', sa.String(length=80), nullable=False),
    sa.Column('problem_url', sa.String(length=500), nullable=False),
    sa.Column('problem_source', sa.String(length=32), nullable=False),
    sa.Column('problem_title', sa.String(length=255), nullable=True),
    sa.Column('problem_path', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('code_text', sa.Text(), nullable=False),
    sa.Column('client_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('fetch_status', sa.String(length=16), nullable=False),
    sa.Column('diagnosis_status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_client_ip_hash'), ['client_ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_problem_path'), ['problem_path'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_public_id'), ['public_id'], unique=True)

    op.create_table('diagnosis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('structured_result_json', sa.JSON(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnosis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnosis_runs_submission_id'), ['submission_id'], unique=False)

    op.create_table('problem_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('normalized_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('sample_input_text', sa.Text(), nullable=True),
    sa.Column('sample_output_text', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('raw_excerpt', sa.Text(), nullable=True),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_snapshots')
    with op.batch_alter_table('diagnosis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnosis_runs_submission_id'))

    op.drop_table('diagnosis_runs')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_public_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_problem_path'))
        batch_op.drop_index(batch_op.f('ix_submissions_created_at'))
        batch_op.drop_index(batch_op.f('ix_submissions_client_ip_hash'))

    op.drop_table('submissions')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_username'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
